# This CI only run once
name: Docker Image CI

on:
  push:
    branches: [ "main1" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: michaln28/faster-docker-build:v0.1
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag michaln28/faster-docker-build:v0.1
    #- name: Push Docker image
    #  run: docker push michaln28/faster-docker-build:v0.1